site_name: Commu-YCYZ
theme:
  language: zh
  name: material
  palette:
    primary: deep purple
    accent: indigo
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.instant

plugins:
  - search:
      separator: '[\s\u200b\-]'


markdown_extensions:
  - admonition # !!!note 格式支持
  - pymdownx.arithmatex: # latex 公式支持
      generic: true
  

extra_javascript:
    - 'src/js/extra.js' # latex 公式支持
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML' # latex 公式支持

nav:
  - 简介:
    - 关于本项目: index.md
  - 数学:
    - 微积分基础: math/basic_calculus.md
    - 行列式: math/determinant.md
  - 物理:
    - 常见模型的深入理解: physics/deeper_understanding_on_regular_models.md
    - 狭义相对论: physics/special_relativity.md