site_name: Commu-YCYZ
theme:
  language: zh
  name: material
  palette:
    primary: deep purple
    accent: indigo
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.instant
    - navigation.footer

plugins:
  - search:
      separator: '[\s\u200b\-]'


markdown_extensions:
  - admonition # !!! 格式支持
  - pymdownx.arithmatex: # latex 公式支持
      generic: true
  - pymdownx.details # 折叠格式 ???
  

extra_javascript:
    - 'src/js/extra.js' # latex 公式支持
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML' # latex 公式支持

copyright: 'Copyright &copy; 2023 Commu-YCYZ'

nav:
  - 关于本站:
    - 简介: index.md
    - 参与贡献: about/to-contribute.md
  - 数学:
    - 圆锥曲线解题方法与思路: math/conics.md
    - 微积分基础: math/basic-calculus.md
    - 行列式: math/determinant.md
  - 物理:
    - 常见模型的深入理解: physics/deeper-understanding-on-regular-models.md
    - 狭义相对论: physics/special-relativity.md