name: Deploy To Tencentcloud Server
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  update-dependencies:
  
    runs-on: ubuntu-22.04
    
    steps:

      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pipenv

      - name: Build Static Page
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python3
          pipenv install
          pipenv run mkdocs build -v
          

      - uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TENCENT_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "site/"
          REMOTE_HOST: ${{ secrets.TENCENT_HOST }}
          REMOTE_USER: ${{ secrets.TENCENT_USER }}
          TARGET: ${{ secrets.TENCENT_WORKING_DIR }}
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
