name: Deploy To Tencentcloud Server
run-name: ${{ github.actor }} is deploying to server
on:
  push:
    branches: master

jobs:
  update-dependencies:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Auto Build
        run: |
          pipenv install
          pipenv run mkdocs build
          minify -ars -o msite site
          cp -rf msite/site/* ${{ secrets.TENCENT_WORKING_DIR }}
